# Generated by Django 6.0.1 on 2026-01-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiggy_DB',
            fields=[
                ('Order_No', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.CharField(max_length=100)),
                ('food_name', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Mobile_No', models.IntegerField()),
            ],
        ),
    ]
